#ifndef DEFS_H
#define DEFS_H

#define SCREEN_WIDTH    (1280U)
#define SCREEN_HEIGHT   (736U)

#define BACKGROUND_RED_COMPONENT    (0x0C)
#define BACKGROUND_GREEN_COMPONENT  (0x04)
#define BACKGROUND_BLUE_COMPONENT   (0x04)
#define BACKGROUND_ALPHA_COMPONENT  (0xFF)

#define SNAKE_SIZE  (16U)

#define SNAKE_HEAD_RED_COMPONENT    (0x73)
#define SNAKE_HEAD_GREEN_COMPONENT  (0x93)
#define SNAKE_HEAD_BLUE_COMPONENT   (0xB3)

#define SNAKE_BODY_RED_COMPONENT    (0xF8)
#define SNAKE_BODY_GREEN_COMPONENT  (0xF8)
#define SNAKE_BODY_BLUE_COMPONENT   (0xFF)

#define FOOD_RED_COMPONENT      (0xF0)
#define FOOD_GREEN_COMPONENT    (0x80)
#define FOOD_BLUE_COMPONENT     (0x80)

#endif
