#ifndef DEFS_H
#define DEFS_H

#define SCREEN_WIDTH   1280
#define SCREEN_HEIGHT  720

#define BACKGROUND_RED_COMPONENT    0x0C
#define BACKGROUND_GREEN_COMPONENT  0x04
#define BACKGROUND_BLUE_COMPONENT   0x04
#define BACKGROUND_ALPHA_COMPONENT  0xFF

#endif
